multitenancy_enabled: true
search_enabled: false
http_api_prefix: /tempo

license:
  path: /etc/get/license/get-license.jwt

auth:
  type: enterprise

server:
  http_listen_port: 8080
  grpc_listen_port: 9095
  log_level: info


distributor:
  log_received_traces: true
  receivers:
    otlp:
      protocols:
        grpc:


storage:
  trace:
    wal:
      path: /data/wal
    backend: s3
    s3:
      bucket: enterprise-traces-data
      endpoint: minio.minio.svc.cluster.local:9000
      access_key: minio
      secret_key: minio123
      insecure: true
      forcepathstyle: true

admin_client:
  storage:
    type: s3
    s3:
      endpoint: minio.minio.svc.cluster.local:9000
      bucket_name: enterprise-traces-admin 
      access_key_id: minio
      secret_access_key: minio123
      insecure: true

