apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gem-tls
  namespace: gem
spec:
  dnsNames:
  - gem.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: gem-tls