apiVersion: v1
kind: Service
metadata:
  name: compactor-headless
  namespace: gem
spec:
  ports:
    - name: gem-http
      port: 9000
      targetPort: http
    - name: gem-grpc
      port: 9095
      targetPort: grpc
    - name: gem-gossip
      port: 7946
      targetPort: gossip
  selector:
    name: compactor
  type: ClusterIP
  publishNotReadyAddresses: true
  clusterIP: None