{
 "title": "Per-instance stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": "flog" }
  ]
 },
 "panels": [
  {
   "title": "Total chunks stored in GiB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "loki_ingester_chunk_stored_bytes_total{tenant=\"flog\"} / 1000000000"
    }
   ]
  },
  {
   "title": "GiBs received total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "loki_distributor_bytes_received_total{tenant=\"$instance\"} / 1000000000"
    }
   ]
  },
  {
   "title": "Ingest Rate in MiB/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(loki_distributor_bytes_received_total{tenant=\"$instance\"}[5m]) / 1000000"
    }
   ]
  }
 ]
}