---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webhook
  namespace: simple-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webhook
  template:
    metadata:
      labels:
        app: simple-webhook
    spec:
      containers:
        - name: simple-webhook
          image: techgnosis/simple-webhook:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
