apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: get
spec:
  type: ClusterIP
  selector:
    name: gateway
  ports:
    - name: gateway-http
      port: 8080
      targetPort: http
  
  