apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent
data:
  agent-config.yml: |
    server:
      log_level: info
      http_listen_port: 12345
        
    tempo:
      configs:
      - name: default
        receivers:
          jaeger:
            protocols:
              grpc: # listens on the default jaeger grpc port: 14250
        remote_write:
          - endpoint: tempo:55680
            insecure: true  # only add this if TLS is not required
        batch:
          timeout: 5s
          send_batch_size: 100
