apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mythical-beasts-tls
  namespace: mythical-beasts
spec:
  dnsNames:
  - mythical-beasts.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: mythical-beasts-tls