target: all

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    num_tokens: 512
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1

chunk_store_config:
  max_look_back_period: 0s

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
    - loki-discovery

storage_config:
  aws:
    endpoint: minio:9000
    access_key_id: minio
    secret_access_key: minio123
    bucketnames: loki-data
    s3forcepathstyle: true
    insecure: true
  boltdb_shipper:
    active_index_directory: /data/boltdb-shipper-active
    cache_location: /data/boltdb-shipper-cache
    cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: s3

schema_config:
  configs:
    - from: 2021-01-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

compactor:
  working_directory: /data/boltdb-shipper-compactor
  shared_store: s3