apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: educates
  namespace: eduk8s
spec:
  dnsNames:
  - "*.educates.lab.home"
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: educates-tls