image:
  repository: grafana/grafana-enterprise

replicas: 1

headlessService: true

adminPassword: admin

persistence:
  enabled: true

plugins:
  - grafana-metrics-enterprise-app
  - grafana-enterprise-logs-app
  - grafana-enterprise-traces-app

ingress:
  enabled: true
  hosts:
  - grafana.lab.home
  tls:
  - secretName: grafana-tls
    hosts:
    - grafana.lab.home

extraConfigmapMounts:
- name: grafana-ldap
  mountPath: /etc/grafana/ldap.toml
  subPath: ldap.toml
  configMap: grafana-ldap
  readOnly: true
- name: grafana-enterprise-license
  mountPath: /var/lib/grafana/license.jwt
  subPath: license.jwt
  configMap: license
  readOnly: true