apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: grafana-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
      containers:
        - name: mysql
          image: mysql:8.0.28
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
        - name: phpmyadmin
          image: phpmyadmin:5.1.1
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: grafana-enterprise
            - name: PMA_PASSWORD
              value: grafana-enterprise
      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: grafana-enterprise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: grafana-enterprise
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
    - name: phpmyadmin
      protocol: TCP
      port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: grafana-enterprise
data:
  MYSQL_ROOT_PASSWORD: grafana-enterprise
  MYSQL_DATABASE: grafana-enterprise
  MYSQL_USER: grafana-enterprise
  MYSQL_PASSWORD: grafana-enterprise
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: phpmyadmin-tls
  namespace: grafana-enterprise
spec:
  dnsNames:
  - phpmyadmin.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: phpmyadmin-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin
  namespace: grafana-enterprise
spec:
  tls:
  - hosts:
      - phpmyadmin.lab.home
    secretName: phpmyadmin-tls
  rules:
  - host: phpmyadmin.lab.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mysql
            port:
              number: 80