apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: grafana-enterprise
spec:
  replicas: 0
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
      containers:
        - name: telegraf
          image: docker.io/telegraf:1.21.3
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
