image:
  repository: grafana/grafana-enterprise
  tag: "9.2.4-ubuntu"

replicas: 1

headlessService: true

adminPassword: admin

persistence:
  enabled: true

env:
  GF_PLUGINS_ORACLE_DATASOURCE_MAX_RESPONSE_SIZE: 512
  GF_DIAGNOSTICS_PROFILING_ENABLED: true
  GF_DIAGNOSTICS_PROFILING_PORT: 8080
  


ingress:
  enabled: true
  hosts:
  - grafana.lab.home
  tls:
  - secretName: grafana-tls
    hosts:
    - grafana.lab.home

extraConfigmapMounts:
- name: grafana-ldap
  mountPath: /etc/grafana/ldap.toml
  subPath: ldap.toml
  configMap: grafana-ldap
  readOnly: true
- name: grafana-enterprise-license
  mountPath: /var/lib/grafana/license.jwt
  subPath: license.jwt
  configMap: license
  readOnly: true