apiVersion: batch/v1
kind: Job
metadata:
  name: k6
  namespace: k6
spec:
  selector:
    app: k6
  completions: 10000
  template:
    metadata:
      labels:
        app: k6
    spec:
      restartPolicy: Never
      volumes:
        - name: k6-hotrod
          configMap:
            name: k6-hotrod
      containers:
        - name: k6
          image: docker.io/grafana/k6:0.37.0
          args: ["run", "/tmp/k6/hotrod.js"]
          volumeMounts:
            - name: k6-hotrod
              mountPath: /tmp/k6