apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: phlare-tls
  namespace: phlare
spec:
  dnsNames:
  - phlare.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: phlare-tls