apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana-enterprise
data:
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        orgId: 1
        url: http://tempo.tempo.svc.cluster.local:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        apiVersion: 1
        jsonData:
          tracesToLogs:
            datasourceUid: loki
            tags: ['job']
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: GEM
        type: prometheus
        uid: gem
        access: proxy
        orgId: 1
        url: http://gem-enterprise-metrics-gateway.gem.svc.cluster.local:8080/api/v1/push
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        apiVersion: 1
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: GEL
        type: loki
        uid: gel
        access: proxy
        orgId: 1
        url: http://enterprise-logs-test-fixture-gateway.gel.svc.cluster.local:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        apiVersion: 1
        jsonData:
          derivedFields:
          - datasourceUid: tempo
            matcherRegex: .*(?:tempo_trace_id=|tempo_trace_id\":\s*\")(.*?)(?:\"|\s).*
            name: "TempoTraceId"
            url: "$${__value.raw}"
          - datasourceUid: tempo
            matcherRegex: (?:traceID|trace_id)=(\w+)
            name: "TraceID"
            url: $${__value.raw}