ingester:
  persistence:
    enabled: true

querier:
  persistence:
    enabled: true

compactor:
  enabled: true
  persistence:
    enabled: true

ruler:
  persistence:
    enabled: true

tempo:
  receivers:
    otlp:
      protocols:
        grpc: