server:
  http_listen_port: 12346
logs:
  positions_directory: /home/james/agent/positions
  configs:
    - name: agent-laptop-journald
      clients:
        - url: https://loki.lab.home/loki/api/v1/push
      scrape_configs:
        - job_name: systemd-journal
          journal:
            labels:
              job: systemd-journal
              food: cake