apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: loki-tls
  namespace: loki
spec:
  dnsNames:
  - loki.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: loki-tls