fullnameOverride: loki

ingester:
  persistence:
    enabled: true

querier:
  persistence:
    enabled: true

compactor:
  enabled: true
  persistence:
    enabled: true

ruler:
  persistence:
    enabled: true

indexGateway:
  persistence:
    enabled: true
