---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compactor-data
  namespace: grafana-labs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compactor
  namespace: grafana-labs
spec:
  selector:
    matchLabels:
      app: compactor
  template:
    metadata:
      labels:
        app: compactor
    spec:
      containers:
        - args:
            - -config.file=/etc/ge-logs/config.yaml
            - -target=compactor
          image: grafana/enterprise-logs:v1.0.0
          imagePullPolicy: IfNotPresent
          name: compactor
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 9095
              name: grpc
            - containerPort: 7946
              name: gossip
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /etc/ge-logs
              name: ge-logs-config
            - mountPath: /etc/ge-logs/license
              name: ge-logs-license
      terminationGracePeriodSeconds: 300
      volumes:
        - name: ge-logs-config
          configMap:
            name: ge-logs-config
        - name: ge-logs-license
          secret:
            secretName: ge-logs-license
        - name: data
          persistentVolumeClaim:
            claimName: compactor-data