[[servers]]
host = "openldap.openldap.svc.cluster.local"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = true
bind_dn = "cn=admin,dc=example,dc=org"
bind_password = 'admin'
search_filter = "(cn=%s)"
search_base_dns = ["dc=example,dc=org"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
group_dn = "cn=Admins,ou=Groups,dc=example,dc=org"
org_role = "Admin"
org_id = 1

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"

