grafana.ini:
  server:
    root_url: https://grafana.lab.home
image:
  repository: grafana/grafana-enterprise
adminPassword: admin
persistence:
  enabled: true
ingress:
  enabled: true
  hosts:
  - grafana.lab.home
  tls:
  - secretName: grafana-tls
    hosts:
    - grafana.lab.home