apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
  namespace: grafana-enterprise
spec:
  selector:
    name: grafana-agent
  ports:
    - name: thrift-compact
      port: 6831
      targetPort: thrift-compact
      protocol: UDP