apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: grafana-agent-prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent-prometheus
subjects:
- kind: ServiceAccount
  name: grafana-agent-prometheus
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-agent-prometheus
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      name: grafana-agent-prometheus
  template:
    metadata:
      labels:
        name: grafana-agent-prometheus
    spec:
      containers:
      - args:
        - -config.file=/etc/agent/agent.yaml
        - -config.expand-env
        command:
        - /bin/agent
        envFrom:
        - secretRef:
            name: grafana-cloud-prometheus-creds
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: grafana/agent:v0.15.0
        imagePullPolicy: IfNotPresent
        name: agent
        ports:
        - containerPort: 8080
          name: http-metrics
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/agent
          name: grafana-agent-prometheus-config
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
      serviceAccount: grafana-agent-prometheus
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - configMap:
          name: grafana-agent-prometheus-config
        name: grafana-agent-prometheus-config
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
  updateStrategy:
    type: RollingUpdate
