apiVersion: v1
kind: Service
metadata:
  name: gel-read
  namespace: gel
spec:
  ports:
    - name: gel-http
      port: 3100
      targetPort: http
    - name: gel-grpc
      port: 9095
      targetPort: grpc
  selector:
    name: gel-read
  type: ClusterIP