config:

  server:
    log_level: info

  compactor:
    sharding_enabled: false

  alertmanager:
    sharding_enabled: false
    sharding_ring:
      replication_factor: 1

  ingester:
    lifecycler:
      ring:
        replication_factor: 1

  admin_client:
    storage:
      type: s3
      s3:
        endpoint: minio.minio.svc.cluster.local:9000
        bucket_name: enterprise-metrics-admin
        access_key_id: minio
        secret_access_key: minio123
        insecure: true

  ruler_storage:
    backend: s3
    s3:
      endpoint: minio.minio.svc.cluster.local:9000
      bucket_name: enterprise-metrics-ruler
      access_key_id: minio
      secret_access_key: minio123
      insecure: true

  alertmanager_storage:
    backend: s3
    s3:
      endpoint: minio.minio.svc.cluster.local:9000
      bucket_name: enterprise-metrics-alertmanager
      access_key_id: minio
      secret_access_key: minio123
      insecure: true

  blocks_storage:
    backend: s3
    s3:
      endpoint: minio.minio.svc.cluster.local:9000
      bucket_name: enterprise-metrics-tsdb
      access_key_id: minio
      secret_access_key: minio123
      insecure: true

  limits:
    cardinality_analysis_enabled: true
