apiVersion: v1
kind: Service
metadata:
  name: gel
  namespace: gel
spec:
  ports:
    - name: gel-http
      port: 3100
      targetPort: http
  selector:
    name: gel
  sessionAffinity: None
  type: ClusterIP