apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mimir-tls
  namespace: mimir
spec:
  dnsNames:
  - mimir.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: mimir-tls