apiVersion: v1
kind: Service
metadata:
  name: mythical-beasts
  namespace: mythical-beasts
spec:
  selector:
    app: mythical-beasts
  ports:
    - name: http
      port: 80
    - name: metrics
      port: 4000
