apiVersion: v1
kind: Service
metadata:
  name: gel-discovery
  namespace: gel
spec:
  clusterIP: None
  ports:
    - name: gel-gossip
      port: 7946
      targetPort: gossip
  selector:
    name: gel