{
 "title": "HotROD Demo",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>HotROD</h1><center>"
   }
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hotrod_frontend_request_latency_sum{namespace=\"hotrod\",error=\"false\",endpoint=\"HTTP-GET-/dispatch\"}[20s]) / rate(hotrod_frontend_request_latency_count{namespace=\"hotrod\",error=\"false\",endpoint=\"HTTP-GET-/dispatch\"}[20s])"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 32, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"hotrod\"}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(hotrod_frontend_requests_total{endpoint=\"HTTP-GET-/dispatch\",error=\"false\", namespace=\"hotrod\"}[20s])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(1 - node_memory_MemFree_bytes{job=\"node_exporter\"} / node_memory_MemTotal_bytes{job=\"node_exporter\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  }
 ]
}