apiVersion: v1
kind: Service
metadata:
  name: gem-enterprise-metrics-compactor
  namespace: gem
  annotations:
    kapp.k14s.io/disable-default-ownership-label-rules: ""
    kapp.k14s.io/disable-default-label-scoping-rules: ""
spec:
  selector:
    app: enterprise-metrics-compactor
  ports:
    - protocol: TCP
      port: 8080
  
