auth:
  type: enterprise

# TODO: Ensure the cluster name is set to match your Grafana Labs License File
cluster_name: gem

license:
  path: /etc/gem/license/gem-license.jwt 

server:
  http_listen_port: 9000
  grpc_listen_port: 9095

gateway:
  proxy:
    default:
      url: http://gem.gem.svc.cluster.local:9000
    admin_api:
      url: http://gem.gem.svc.cluster.local:9000
    alertmanager:
      url: http://alertmanager.gem.svc.cluster.local:9000
    compactor:
      url: http://compactor.gem.svc.cluster.local:9000
    distributor:
      url: http://gem.gem.svc.cluster.local:9000
    ingester:
      url: http://gem.gem.svc.cluster.local:9000
    query_frontend:
      url: http://gem.gem.svc.cluster.local:9000
    ruler:
      url: http://gem.gem.svc.cluster.local:9000
    store_gateway:
      url: http://gem.gem.svc.cluster.local:9000
    

alertmanager_storage:
  backend: s3
  s3:
    endpoint: minio.minio.svc.cluster.local:9000
    bucket_name: enterprise-metrics-alertmanager
    access_key_id: minio
    secret_access_key: minio123
    insecure: true


store_gateway:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist

ruler:
  enable_sharding: true
  ring:
    kvstore:
      store: memberlist

ruler_storage:
  backend: s3
  s3:
    endpoint: minio.minio.svc.cluster.local:9000
    bucket_name: enterprise-metrics-ruler
    access_key_id: minio
    secret_access_key: minio123
    insecure: true

admin_client:
  storage:
    type: s3
    s3:
      endpoint: minio.minio.svc.cluster.local:9000
      bucket_name: enterprise-metrics-admin 
      access_key_id: minio
      secret_access_key: minio123
      insecure: true

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - gem-discovery

ingester:
  lifecycler:
    num_tokens: 512
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3

compactor:
  data_dir: "/data"
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist

alertmanager:
  data_dir: /data/alertmanager
  external_url: /alertmanager
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist

blocks_storage:
  tsdb:
    dir: /data/cortex/tsdb
  bucket_store:
    sync_dir: /data/cortex/tsdb-sync
  backend: s3
  s3:
    endpoint: minio.minio.svc.cluster.local:9000
    bucket_name: enterprise-metrics-tsdb
    access_key_id: minio
    secret_access_key: minio123 
    insecure: true

storage:
  engine: blocks

limits:
  cardinality_analysis_enabled: true

instrumentation:
  enabled: true
  distributor_client:
    address: 'dns:///gem:9095'