apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: gem
spec:
  type: ClusterIP
  selector:
    name: gateway
  ports:
    - name: gateway-http
      port: 9000
      targetPort: http
  
  