apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: opentelemetry-demo-tls
  namespace: opentelemetry-demo
spec:
  dnsNames:
  - opentelemetry-demo.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: opentelemetry-demo-tls