grafana:
  enabled: true
  adminPassword: admin
  ingress:
    enabled: true
    hosts:
    - grafana.lab.home
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.lab.home

promtail:
  enabled: false

prometheus:
  enabled: true
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  alertmanager:
    enabled: false
  pushGateway:
    enabled: false
  server:
    enabled: true
    ingress:
      enabled: true
      hosts:
      - prometheus.lab.home
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.lab.home
    persistentVolume:
      enabled: true
  

loki:
  ingress:
    enabled: true
    hosts:
    - host: loki.lab.home
      paths:
      - /
    tls:
    - secretName: loki-tls
      hosts:
      - loki.lab.home
  persistence:
    enabled: true