apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
  namespace: agent
data:
  agent.yaml: |
    server:
      http_listen_port: 12345
    logs:
      positions_directory: /tmp/positions
      configs:
        - name: interlake
          clients:
            - url: http://gel.gel.svc.cluster.local:3100/loki/api/v1/push
              basic_auth:
                  username: interlake
                  password: aW50ZXJsYWtlLWFsbC1hbGw6aDE2PzF7eSsyMmZGKzEuNCkmMz8qMTkh
          scrape_configs:
            - job_name: gem-pods
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - gem
              pipeline_stages:
                - docker: {}
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: __host__
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
            - job_name: grafana-pods
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - grafana-enterprise
              pipeline_stages:
                - docker: {}
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: __host__
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
            - job_name: tempo-pods
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - tempo
              pipeline_stages:
                - docker: {}
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: __host__
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
            - job_name: gel-pods
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - gel
              pipeline_stages:
                - docker: {}
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: __host__
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
    metrics:
      configs:
        - name: interlake
          host_filter: true
          remote_write:
            - url: http://gem-enterprise-metrics-gateway.gem.svc.cluster.local:8080/api/v1/push
              basic_auth:
                username: interlake
                password: aW50ZXJsYWtlLWludGVybGFrZToiPCg4JH44eTM2M0E0dTQ2JnkoOCJ7NSQ=
          scrape_configs:
            - job_name: gel-pods
              metrics_path: "/metrics"
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - gel
              relabel_configs:
                - action: drop
                  regex: Succeeded|Failed
                  source_labels:
                    - __meta_kubernetes_pod_phase
                - action: keep
                  regex: 3100
                  source_labels:
                    - __meta_kubernetes_pod_container_port_number
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
            - job_name: grafana-enterprise-pods
              metrics_path: "/metrics"
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - grafana-enterprise
              relabel_configs:
                - action: drop
                  regex: Succeeded|Failed
                  source_labels:
                    - __meta_kubernetes_pod_phase
                - action: keep
                  regex: 3000
                  source_labels:
                    - __meta_kubernetes_pod_container_port_number
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
            - job_name: tempo-pods
              metrics_path: "/metrics"
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - tempo
              relabel_configs:
                - action: drop
                  regex: Succeeded|Failed
                  source_labels:
                    - __meta_kubernetes_pod_phase
                - action: keep
                  regex: 3100
                  source_labels:
                    - __meta_kubernetes_pod_container_port_number
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
      global:
        scrape_interval: 5s
      wal_directory: /var/lib/agent/data
    traces:
      configs:
        - name: interlake
          remote_write:
            - endpoint: get.get.svc.cluster.local:4317
              protocol: grpc
              insecure: true
              basic_auth:
                username: test2
                password: dGVzdDItdGVzdDI6XzY1aissOTZ9MzF8XVwycm1FNn05Py4y
          receivers:
            jaeger:
              protocols:
                thrift_compact:
    integrations:
      prometheus_remote_write:
        - url: http://gateway.gem.svc.cluster.local:9000/api/v1/push
          basic_auth:
            username: interlake
            password: aW50ZXJsYWtlLWFsbC1hbGw6PGE0JS00Wz4+SnhfNzREODMyLVszLTMx
      node_exporter:
        enabled: true
        rootfs_path: /
        sysfs_path: /sys
        procfs_path: /proc
