apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
  namespace: grafana-labs
spec:
  ports:
    - name: zipkin
      port: 9411
    - name: thrifthttp
      port: 14268
    - name: api
      port: 12345
  type: ClusterIP
  selector:
    name: grafana-agent