apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: get-tls
  namespace: get
spec:
  dnsNames:
  - get.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: get-tls