auth:
  type: enterprise

# TODO: Ensure the cluster name is set to match your Grafana Labs License File
cluster_name: get

license:
  path: /etc/get/license/get-license.jwt 

server:
  http_listen_port: 8080

gateway:
  proxy:
    admin_api:
      url: http://gem.gem.svc.cluster.local:8080
    alertmanager:
      url: http://alertmanager.gem.svc.cluster.local:8080
    compactor:
      url: http://compactor.gem.svc.cluster.local:8080
    distributor:
      url: http://gem.gem.svc.cluster.local:8080
    ingester:
      url: http://gem.gem.svc.cluster.local:8080
    query_frontend:
      url: http://gem.gem.svc.cluster.local:8080
    ruler:
      url: http://gem.gem.svc.cluster.local:8080
    store_gateway:
      url: http://gem.gem.svc.cluster.local:8080
    

admin_client:
  storage:
    type: s3
    s3:
      endpoint: minio:9000
      bucket_name: enterprise-metrics-admin 
      access_key_id: minio
      secret_access_key: minio123
      insecure: true


memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - get-discovery

ingester:
  lifecycler:
    num_tokens: 512
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3

compactor:
  data_dir: "/data"
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist

blocks_storage:
  tsdb:
    dir: /data/cortex/tsdb
  bucket_store:
    sync_dir: /data/cortex/tsdb-sync
  backend: s3
  s3:
    endpoint: minio:9000
    bucket_name: enterprise-metrics-tsdb
    access_key_id: minio
    secret_access_key: minio123 
    insecure: true

storage:
  engine: blocks