auth_enabled: true
multitenancy_enabled: true
search_enabled: true

license:
  path: /etc/get/license/get-license.jwt

auth:
  type: enterprise

server:
  http_listen_port: 8080

ingester:
  lifecycler:
    ring:
      replication_factor: 3

compactor:
  ring:
    kvstore:
      store: memberlist

storage:
  trace:
    wal:
      path: /data/wal
    backend: s3
    s3:
      bucket: enterprise-traces-data
      endpoint: minio.minio.svc.cluster.local:9000
      access_key: minio
      secret_key: minio123
      insecure: true
      forcepathstyle: true

gateway:
  proxy:
    admin_api:
      url: http://get.get.svc.cluster.local:8080
    compactor:
      url: http://compactor.get.svc.cluster.local:8080
    distributor:
      url: http://get.get.svc.cluster.local:8080
    ingester:
      url: http://get.get.svc.cluster.local:8080
    query_frontend:
      url: http://get.get.svc.cluster.local:8080
    

admin_client:
  storage:
    type: s3
    s3:
      endpoint: minio.minio.svc.cluster.local:9000
      bucket_name: enterprise-traces-admin 
      access_key_id: minio
      secret_access_key: minio123
      insecure: true


memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - get-discovery
