apiVersion: v1
kind: Service
metadata:
  name: get-headless
  namespace: get
spec:
  ports:
    - name: get-http
      port: 8080
      targetPort: http
    - name: get-grpc
      port: 9095
      targetPort: grpc
    - name: get-thrift-compact
      port: 6831
      targetPort: thrift-compact
  selector:
    name: get
  type: ClusterIP
  clusterIP: None