apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: minio
  namespace: minio
spec:
  dnsNames:
  - minio.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: minio-tls