buckets:
  - name: enterprise-logs-data
    policy: none
    purge: false
  - name: enterprise-logs-admin
    policy: none
    purge: false
  - name: enterprise-logs-ruler
    policy: none
    purge: false
  - name: enterprise-metrics-tsdb
    policy: none
    purge: false
  - name: enterprise-metrics-admin
    policy: none
    purge: false
  - name: enterprise-metrics-ruler
    policy: none
    purge: false
  - name: enterprise-metrics-alertmanager
    policy: none
    purge: false
  - name: enterprise-traces-data
    policy: none
    purge: false
  - name: enterprise-traces-admin
    policy: none
    purge: false
  - name: loki-data
    policy: none
    purge: false
  - name: loki-ruler
    policy: none
    purge: false
  - name: mimir-data
    policy: none
    purge: false
  - name: mimir-ruler
    policy: none
    purge: false
  - name: mimir-alertmanager
    policy: none
    purge: false
persistence:
  size: 100Gi
accessKey: minio
secretKey: minio123