apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: db
        image: grafana/tns-db:9c1ab38
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        ports:
        - containerPort: 80
        env:
        - name: JAEGER_AGENT_HOST
          value: jaeger
        - name: JAEGER_ENDPOINT
          value: "http://tempo.grafana-labs.svc.cluster.local:14268/api/traces"
        - name: JAEGER_TAGS
          value: cluster=docker,namespace=default
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"