apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-traces
  namespace: grafana-agent-traces
data:
  agent.yaml: |
    tempo:
      configs:
      - name: jaeger-only
        batch:
            send_batch_size: 1000
            timeout: 5s
        receivers:
          jaeger:
            protocols:
              thrift_http: null
        remote_write:
          - endpoint: ${TEMPO_ENDPOINT}
