apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: redis-tls
  namespace: redis
spec:
  dnsNames:
  - redis.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: redis-tls